### PR TITLE
Added jest and vue testing library, plus dependencies

### PR DESCRIPTION
**Pull request by rb1193**
## Description

This PR adds Jest and Vue testing library to the project dependencies. I have found myself setting this up in a few projects now so I thought I would save myself the hassle going forward and see if you guys think it's worth including in the starter. There are only dev dependencies included so there is no cost in terms of final build size.

I'm not running it through Webpack at the moment because the Jest docs for webpack basically say "[here be dragons](https://jestjs.io/docs/en/getting-started#using-webpack)". If that's something you think worth exploring though then I'd be happy to look into it. In my experience just transpiling via Babel works perfectly well, at the cost of an extra babel config file in the repo and a couple of extra top level deps in package.json.

I'm also not quite sure where the test setup file should live so I just dropped in the JS folder for now, any bright ideas on that let me know.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- [ ] Run `npm install && npm run test` and confirm HelloWorld.spec.js passes

## Checklist:

- [x] My branch is up to date with master
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings and debugging code has been removed

### CODE REVIEW

**Comment by hatzipanis** [comment]
Great contribution @rb1193!

**Comment by judereid** [comment]
Nice one - looks good to me!

**Review by moacode — CHANGES_REQUESTED** [review]
Just had a chat to Ryan about this. Great contribution but unfortunately the babel config overrides the config we've defined in the webpack package. Ryan's gonna investigate how to get Jest working with Webpack and then submit a PR to the webpack repository (good luck!).

**Comment by moacode** [comment]
☝️ @rb1193 found a simpler solution of configuring babel via the `jest.config.js` file.

**Comment by hatzipanis** [comment]
Nice work @rb1193 @thejoshsmith

**Pull request merged**
