### PR TITLE
Adds installation script

### LINKED ISSUE #20: System Name not set after install
On a recent install the System Name in the Control Panel is set to _Batch Craft Starter_ even though during the Craft install (`fin exec craft install`) I entered a new project's name. Oddly the project's meta title does seem to get changed.

### PR DESCRIPTION
**Pull request by judereid**
## Description
This came out of attempts to resolve #20. 

As far as I can work out, if there is no system entry in the project.yaml, the system name gets set correctly but Twigpack doesn't install automatically. If there is, the name property doesn't get set during setup. So out of frustration I just removed both entries in project.yaml.

This means you have to install Twigpack manually after the craft setup which added a step to the installation process. To counter that, I have added a bash script to Docksal that does the installation for you, removing all the steps.

So now, we just need to create-project, update docksal.env and run `fin batch/install` and it the project should be up and running, with Twigpack installed and the correct system name.

Fixes #20 

## Type of change
 New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
 Tested the create-project and install steps locally.

### CODE REVIEW

**Comment by judereid** [comment]
@hatzipanis The command for testing this branch is 

`fin rc composer create-project batch/craft-starter {project} dev-feat/install-script -s dev`

After that, you should just be able to run `fin batch/install` as per the [readme](https://github.com/batchnz/craft/blob/feat/install-script/README.md)

**Comment by hatzipanis** [comment]
Thanks @judereid. Overall really good and worked perfectly! And `post-create-project-cmd` ran fine when I setup a new project this time so nothing needed there (obviously user error). 

Let's chat about removing the default `$SITE_NAME` as discussed?

Aside from that there's a few changes I want to make to the README so will get that done in the next few days.

**Comment by hatzipanis** [comment]
@judereid I've made some minor changes to the README that I was talking about. When you get back in we can discuss the remaining bits then we're good!

**Review by hatzipanis — APPROVED** [review]
Approved! 🎉

**Pull request merged**
