### PR TITLE
fix(project config): Fix project configuration location, configure to…

### PR DESCRIPTION
**Pull request by judereid**
## Description

This PR updates the location of project.yaml file, and updates the contents to use the correct version and install the Twigpack plugin by default.

### CODE REVIEW

**Comment by judereid** [comment]
@thejoshsmith Could you double-check this one for me please? Haven't worked with this config file much so not totally sure, but this seems to work!

**Comment by moacode** [comment]
Not a problem @judereid, testing now!

**Review by moacode — APPROVED** [review]
Looks good @judereid, I've added the twigpack plugin to composer.json as Craft looks for the package when processing the project config yaml file and will fail if it's not there!

**Comment by judereid** [comment]
@thejoshsmith I reverted the composer.json change as Twigpack (as well as some other plugins) are included in the [composer.json.default](https://github.com/batchnz/craft/blob/master/composer.json.default) which gets swapped out during the post-create-project-cmd (so only gets applied if you use create-project when setting up).

**Comment by moacode** [comment]
Ahh of course—Thanks. I tested on a previously installed version 🤦

**Pull request merged**
